/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 03 13:33:36 GMT 2017
 */

package io.reactivex.internal.schedulers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.reactivex.internal.schedulers.RxThreadFactory;
import io.reactivex.internal.schedulers.SchedulerPoolFactory;
import java.util.concurrent.ThreadFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SchedulerPoolFactory_ESTest extends SchedulerPoolFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SchedulerPoolFactory.create((ThreadFactory) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.concurrent.ThreadPoolExecutor", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SchedulerPoolFactory.start();
      SchedulerPoolFactory.ScheduledTask schedulerPoolFactory_ScheduledTask0 = new SchedulerPoolFactory.ScheduledTask();
      schedulerPoolFactory_ScheduledTask0.run();
      RxThreadFactory rxThreadFactory0 = new RxThreadFactory((String) null);
      SchedulerPoolFactory.create(rxThreadFactory0);
      SchedulerPoolFactory.create(rxThreadFactory0);
      SchedulerPoolFactory.shutdown();
      SchedulerPoolFactory.start();
      SchedulerPoolFactory.shutdown();
      SchedulerPoolFactory.start();
  }
}
