/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Aug 03 13:14:48 GMT 2017
 */

package io.reactivex.internal.schedulers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class InstantPeriodicTask_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "io.reactivex.internal.schedulers.InstantPeriodicTask"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/Fortaleza"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(InstantPeriodicTask_ESTest_scaffolding.class.getClassLoader() ,
      "io.reactivex.functions.BiFunction",
      "io.reactivex.internal.fuseable.ScalarCallable",
      "io.reactivex.internal.operators.flowable.FlowableWindow",
      "io.reactivex.internal.schedulers.RxThreadFactory$RxCustomThread",
      "io.reactivex.exceptions.UndeliverableException",
      "io.reactivex.internal.operators.flowable.FlowableIntervalRange",
      "io.reactivex.functions.LongConsumer",
      "io.reactivex.Scheduler$Worker",
      "io.reactivex.internal.schedulers.SchedulerWhen",
      "io.reactivex.internal.util.ErrorMode",
      "io.reactivex.internal.operators.flowable.FlowableAmb",
      "io.reactivex.internal.schedulers.ScheduledRunnable",
      "io.reactivex.internal.operators.flowable.FlowableObserveOn",
      "io.reactivex.internal.fuseable.HasUpstreamPublisher",
      "io.reactivex.FlowableSubscriber",
      "io.reactivex.internal.operators.completable.CompletableTimer",
      "io.reactivex.internal.operators.flowable.AbstractFlowableWithUpstream",
      "io.reactivex.internal.operators.flowable.FlowableConcatArray",
      "io.reactivex.internal.operators.completable.CompletablePeek",
      "io.reactivex.internal.functions.Functions$NaturalObjectComparator",
      "io.reactivex.internal.operators.flowable.FlowableSequenceEqualSingle",
      "io.reactivex.internal.operators.observable.ObservableTimer",
      "io.reactivex.internal.operators.observable.ObservableWindowBoundarySupplier",
      "io.reactivex.internal.functions.Functions$EmptyLongConsumer",
      "io.reactivex.functions.BiConsumer",
      "io.reactivex.internal.operators.completable.CompletableLift",
      "io.reactivex.Maybe",
      "io.reactivex.internal.operators.flowable.FlowableLift",
      "io.reactivex.internal.subscriptions.SubscriptionHelper",
      "io.reactivex.Observable",
      "io.reactivex.internal.util.NotificationLite",
      "io.reactivex.internal.functions.ObjectHelper",
      "io.reactivex.exceptions.MissingBackpressureException",
      "io.reactivex.internal.schedulers.RxThreadFactory",
      "io.reactivex.internal.operators.flowable.FlowableWindowBoundarySelector",
      "io.reactivex.internal.util.Pow2",
      "io.reactivex.internal.operators.flowable.FlowableJust",
      "io.reactivex.functions.Predicate",
      "io.reactivex.internal.operators.observable.ObservableWindowTimed",
      "io.reactivex.internal.schedulers.InstantPeriodicTask",
      "io.reactivex.SingleObserver",
      "io.reactivex.internal.operators.observable.ObservableFlatMap",
      "io.reactivex.internal.schedulers.SingleScheduler$ScheduledWorker",
      "io.reactivex.internal.operators.single.SingleDelay",
      "io.reactivex.internal.operators.flowable.FlowableRepeat",
      "io.reactivex.internal.operators.flowable.FlowableRangeLong",
      "io.reactivex.internal.operators.observable.ObservableCombineLatest",
      "io.reactivex.internal.operators.observable.ObservableWindowBoundarySelector",
      "io.reactivex.internal.operators.single.SingleDoOnSubscribe",
      "io.reactivex.MaybeObserver",
      "io.reactivex.SingleSource",
      "io.reactivex.internal.operators.single.SingleDoAfterTerminate",
      "io.reactivex.internal.operators.observable.ObservableJust",
      "io.reactivex.internal.operators.flowable.FlowableSingleSingle",
      "io.reactivex.internal.operators.single.SingleTimer",
      "io.reactivex.internal.schedulers.NewThreadScheduler",
      "io.reactivex.internal.operators.flowable.FlowableConcatMapEager",
      "io.reactivex.internal.operators.parallel.ParallelFromArray",
      "io.reactivex.internal.operators.maybe.MaybePeek",
      "io.reactivex.internal.fuseable.HasUpstreamObservableSource",
      "io.reactivex.internal.operators.flowable.FlowableFromFuture",
      "io.reactivex.plugins.RxJavaPlugins",
      "io.reactivex.internal.fuseable.HasUpstreamMaybeSource",
      "io.reactivex.disposables.Disposable",
      "io.reactivex.internal.operators.maybe.MaybeDelay",
      "io.reactivex.internal.operators.observable.ObservableFromArray",
      "io.reactivex.internal.functions.Functions$EmptyAction",
      "io.reactivex.internal.subscriptions.EmptySubscription",
      "io.reactivex.internal.schedulers.SingleScheduler",
      "io.reactivex.internal.operators.observable.ObservableRepeat",
      "io.reactivex.internal.operators.maybe.MaybeDoOnEvent",
      "io.reactivex.internal.operators.flowable.FlowableFromCallable",
      "io.reactivex.internal.operators.flowable.FlowableDefer",
      "io.reactivex.flowables.ConnectableFlowable",
      "io.reactivex.internal.schedulers.AbstractDirectTask",
      "io.reactivex.Single",
      "io.reactivex.internal.operators.observable.ObservableSingleSingle",
      "io.reactivex.ObservableSource",
      "io.reactivex.internal.functions.Functions$Identity",
      "org.reactivestreams.Subscriber",
      "io.reactivex.internal.util.OpenHashSet",
      "io.reactivex.internal.operators.observable.ObservableLift",
      "io.reactivex.internal.operators.flowable.FlowableConcatMapEagerPublisher",
      "io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle",
      "io.reactivex.internal.operators.observable.ObservableFromFuture",
      "io.reactivex.functions.Consumer",
      "io.reactivex.internal.operators.observable.ObservableConcatMap",
      "io.reactivex.internal.operators.observable.ObservableFromCallable",
      "io.reactivex.functions.Function",
      "org.reactivestreams.Subscription",
      "io.reactivex.internal.schedulers.SchedulerWhen$SubscribedDisposable",
      "io.reactivex.internal.operators.observable.ObservableDoFinally",
      "io.reactivex.internal.operators.completable.CompletableConcatArray",
      "io.reactivex.Completable",
      "io.reactivex.internal.operators.observable.ObservableObserveOn",
      "io.reactivex.internal.operators.parallel.ParallelSortedJoin",
      "io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain",
      "io.reactivex.internal.operators.observable.ObservableFromPublisher",
      "io.reactivex.internal.fuseable.FuseToObservable",
      "io.reactivex.internal.disposables.DisposableContainer",
      "io.reactivex.internal.operators.observable.ObservableToListSingle",
      "io.reactivex.internal.operators.flowable.FlowableCache",
      "io.reactivex.CompletableObserver",
      "io.reactivex.internal.operators.flowable.FlowableDoFinally",
      "io.reactivex.internal.operators.maybe.MaybeConcatArray",
      "io.reactivex.internal.operators.observable.ObservableAmb",
      "io.reactivex.internal.functions.Functions",
      "io.reactivex.internal.functions.Functions$TruePredicate",
      "io.reactivex.internal.operators.observable.ObservableDoOnLifecycle",
      "io.reactivex.internal.operators.flowable.FlowableDelay",
      "io.reactivex.CompletableSource",
      "io.reactivex.internal.operators.parallel.ParallelJoin",
      "io.reactivex.internal.operators.observable.ObservableFromUnsafeSource",
      "io.reactivex.internal.functions.Functions$EmptyConsumer",
      "io.reactivex.MaybeSource",
      "io.reactivex.internal.schedulers.IoScheduler",
      "io.reactivex.internal.operators.single.SingleDoOnEvent",
      "io.reactivex.internal.schedulers.ComputationScheduler",
      "io.reactivex.internal.operators.flowable.FlowableUsing",
      "io.reactivex.exceptions.CompositeException$PrintStreamOrWriter",
      "io.reactivex.internal.operators.flowable.FlowableFromIterable",
      "io.reactivex.exceptions.CompositeException$WrappedPrintWriter",
      "io.reactivex.internal.operators.observable.ObservableDelay",
      "io.reactivex.internal.operators.flowable.FlowableZip",
      "io.reactivex.internal.functions.Functions$EmptyRunnable",
      "io.reactivex.internal.operators.observable.AbstractObservableWithUpstream",
      "io.reactivex.Flowable",
      "io.reactivex.internal.operators.completable.CompletableDoOnEvent",
      "io.reactivex.internal.schedulers.SchedulerPoolFactory",
      "io.reactivex.BackpressureStrategy",
      "io.reactivex.internal.operators.observable.ObservableIntervalRange",
      "io.reactivex.internal.fuseable.QueueFuseable",
      "io.reactivex.internal.operators.completable.CompletableDoFinally",
      "org.reactivestreams.Publisher",
      "io.reactivex.BackpressureOverflowStrategy",
      "io.reactivex.internal.operators.flowable.FlowableWindowBoundary",
      "io.reactivex.internal.schedulers.IoScheduler$EventLoopWorker",
      "io.reactivex.internal.operators.observable.ObservableUsing",
      "io.reactivex.internal.fuseable.QueueSubscription",
      "io.reactivex.internal.fuseable.FuseToFlowable",
      "io.reactivex.internal.schedulers.IoScheduler$ThreadWorker",
      "io.reactivex.internal.operators.observable.ObservableDefer",
      "io.reactivex.internal.operators.observable.ObservableFromIterable",
      "io.reactivex.internal.functions.Functions$OnErrorMissingConsumer",
      "io.reactivex.Observer",
      "io.reactivex.internal.fuseable.SimpleQueue",
      "io.reactivex.internal.operators.parallel.ParallelPeek",
      "io.reactivex.internal.schedulers.NewThreadWorker",
      "io.reactivex.internal.functions.Functions$NullCallable",
      "io.reactivex.functions.BiPredicate",
      "io.reactivex.internal.operators.maybe.MaybeDelayOtherPublisher",
      "io.reactivex.parallel.ParallelFlowable",
      "io.reactivex.exceptions.CompositeException$WrappedPrintStream",
      "io.reactivex.internal.schedulers.NonBlockingThread",
      "io.reactivex.internal.operators.flowable.FlowableFromPublisher",
      "io.reactivex.internal.operators.single.SingleDoOnError",
      "io.reactivex.internal.operators.observable.ObservableWindowBoundary",
      "io.reactivex.disposables.CompositeDisposable",
      "io.reactivex.internal.operators.flowable.FlowableWindowBoundarySupplier",
      "io.reactivex.exceptions.CompositeException",
      "io.reactivex.internal.operators.flowable.FlowableToListSingle",
      "io.reactivex.internal.operators.flowable.FlowableCombineLatest",
      "io.reactivex.internal.operators.flowable.FlowableFromArray",
      "io.reactivex.functions.BooleanSupplier",
      "io.reactivex.internal.operators.flowable.FlowableTimer",
      "io.reactivex.internal.schedulers.SchedulerWhen$QueueWorker",
      "io.reactivex.internal.operators.maybe.MaybeToFlowable",
      "io.reactivex.internal.operators.maybe.MaybeTimer",
      "io.reactivex.internal.functions.Functions$MaxRequestSubscription",
      "io.reactivex.Scheduler",
      "io.reactivex.internal.operators.maybe.MaybeDoFinally",
      "io.reactivex.internal.functions.Functions$FalsePredicate",
      "io.reactivex.internal.operators.flowable.FlowableConcatMap",
      "io.reactivex.observables.ConnectableObservable",
      "io.reactivex.internal.schedulers.ComputationScheduler$EventLoopWorker",
      "io.reactivex.internal.functions.Functions$ErrorConsumer",
      "io.reactivex.internal.functions.ObjectHelper$BiObjectPredicate",
      "io.reactivex.functions.Action",
      "io.reactivex.exceptions.ProtocolViolationException",
      "io.reactivex.functions.Function3",
      "io.reactivex.functions.Function5",
      "io.reactivex.functions.Function4",
      "io.reactivex.internal.schedulers.ComputationScheduler$PoolWorker",
      "io.reactivex.functions.Function7",
      "io.reactivex.exceptions.OnErrorNotImplementedException",
      "io.reactivex.functions.Function6",
      "io.reactivex.functions.Function9",
      "io.reactivex.functions.Function8",
      "io.reactivex.internal.operators.observable.ObservableWindow",
      "io.reactivex.internal.operators.completable.CompletableDelay",
      "io.reactivex.internal.operators.single.SingleDoOnDispose",
      "io.reactivex.internal.operators.flowable.FlowableWindowTimed",
      "io.reactivex.internal.operators.maybe.AbstractMaybeWithUpstream"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("io.reactivex.functions.Consumer", false, InstantPeriodicTask_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.util.concurrent.Callable", false, InstantPeriodicTask_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.util.function.Supplier", false, InstantPeriodicTask_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(InstantPeriodicTask_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "io.reactivex.internal.functions.Functions",
      "io.reactivex.internal.schedulers.InstantPeriodicTask",
      "io.reactivex.plugins.RxJavaPlugins",
      "io.reactivex.internal.schedulers.RxThreadFactory",
      "io.reactivex.internal.schedulers.AbstractDirectTask",
      "io.reactivex.internal.functions.ObjectHelper",
      "io.reactivex.internal.schedulers.ScheduledRunnable",
      "io.reactivex.internal.util.OpenHashSet",
      "io.reactivex.exceptions.UndeliverableException"
    );
  }
}
